# Generated by Django 4.2.2 on 2023-06-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_cars_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
