# Generated by Django 4.2.2 on 2023-06-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_remove_cars_title_cars_brand_cars_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo '),
        ),
    ]
