# Generated by Django 4.2.2 on 2023-06-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_cars_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='category',
            field=models.CharField(choices=[('car', 'Auto'), ('pickup', 'Camioneta'), ('comercial', 'Comercial'), ('suv', 'SUV'), ('cross', 'CrossOver')], default='car', max_length=30, verbose_name='Categoria'),
        ),
    ]
